import { jsonSchemaOutputFormat } from "@anthropic-ai/sdk/helpers/json-schema";

const salesNotesExtractSchema = {
  type: "object",
  properties: {
    summary: { type: "string" },
    painPoints: { type: "array", items: { type: "string" } },
    goals: { type: "array", items: { type: "string" } },
    agencyFrustrations: { type: "array", items: { type: "string" } },
    purchasedServices: {
      type: "array",
      items: { type: "string", enum: ["seo", "ppc", "orm", "social"] },
    },
    purchasedProductLabels: { type: "array", items: { type: "string" } },
    clinicalDifferentiator: { type: "string" },
    primaryProcedures: { type: "array", items: { type: "string" } },
    clientRunsOwnAds: { type: "boolean" },
    adsPerformanceNote: { type: "string" },
    vendorPlatforms: { type: "array", items: { type: "string" } },
    ormProgramName: { type: "string" },
    socialContentThemes: { type: "array", items: { type: "string" } },
    primarySocialPlatform: { type: "string" },
    socialAdsHistory: { type: "string" },
    operationalBottlenecks: { type: "array", items: { type: "string" } },
    capacityNotes: { type: "string" },
    vendorFrustrations: { type: "array", items: { type: "string" } },
    staffConstraints: { type: "string" },
    doctorCount: { type: "string" },
    clientPersonaTone: { type: "string", enum: ["standard", "no-nonsense"] },
  },
  required: [
    "summary",
    "painPoints",
    "goals",
    "agencyFrustrations",
    "purchasedServices",
    "purchasedProductLabels",
    "clinicalDifferentiator",
    "primaryProcedures",
    "clientRunsOwnAds",
    "adsPerformanceNote",
    "vendorPlatforms",
    "ormProgramName",
    "socialContentThemes",
    "primarySocialPlatform",
    "socialAdsHistory",
    "operationalBottlenecks",
    "capacityNotes",
    "vendorFrustrations",
    "staffConstraints",
    "doctorCount",
    "clientPersonaTone",
  ],
  additionalProperties: false,
} as const;

export const salesNotesExtractOutputFormat = jsonSchemaOutputFormat(
  salesNotesExtractSchema,
);
